#!/usr/bin/env bun

/**
 * iClone — Interactive setup script.
 *
 * Walks a fresh clone through:
 *   1. Bun version check
 *   2. Convex deployment provisioning (delegates to `bunx convex dev --once`)
 *   3. `.env.local` generation
 *   4. Convex-side env vars (Resend, Google OAuth, state secret)
 *   5. Optional: promote first admin
 *
 * Idempotent — running it again merges new values without overwriting
 * existing ones unless the user confirms.
 *
 * Run:  bun run setup
 */

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createInterface } from "node:readline/promises";
import { exportJWK, exportPKCS8, generateKeyPair } from "jose";

const ROOT = process.cwd();
const ENV_PATH = join(ROOT, ".env.local");

const c = {
	reset: "\x1b[0m",
	bold: "\x1b[1m",
	dim: "\x1b[2m",
	cyan: "\x1b[36m",
	green: "\x1b[32m",
	yellow: "\x1b[33m",
	red: "\x1b[31m",
	blue: "\x1b[34m",
};

const rl = createInterface({ input: process.stdin, output: process.stdout });

function log(msg: string) {
	console.log(msg);
}

function header(title: string) {
	log("");
	log(`${c.bold}${c.cyan}━━━ ${title} ━━━${c.reset}`);
}

function info(msg: string) {
	log(`${c.dim}${msg}${c.reset}`);
}

function ok(msg: string) {
	log(`${c.green}✓${c.reset} ${msg}`);
}

function warn(msg: string) {
	log(`${c.yellow}!${c.reset} ${msg}`);
}

function fail(msg: string): never {
	log(`${c.red}✗${c.reset} ${msg}`);
	process.exit(1);
}

async function ask(question: string, fallback?: string): Promise<string> {
	const suffix = fallback ? ` ${c.dim}(${fallback})${c.reset}` : "";
	const answer = (await rl.question(`${question}${suffix}: `)).trim();
	return answer || fallback || "";
}

async function askSecret(question: string): Promise<string> {
	// readline doesn't natively mask input — for a true masked prompt
	// you'd need a TTY hack. Keep it simple: warn the user.
	info("(input will be visible — clear your shell history if sensitive)");
	const answer = (await rl.question(`${question}: `)).trim();
	return answer;
}

async function confirm(question: string, defaultYes = true): Promise<boolean> {
	const def = defaultYes ? "Y/n" : "y/N";
	const a = (await rl.question(`${question} [${def}] `)).trim().toLowerCase();
	if (!a) return defaultYes;
	return a === "y" || a === "yes" || a === "o" || a === "oui";
}

function parseEnv(content: string): Map<string, string> {
	const out = new Map<string, string>();
	for (const line of content.split("\n")) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#")) continue;
		const eq = trimmed.indexOf("=");
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		let val = trimmed.slice(eq + 1).trim();
		if (
			(val.startsWith('"') && val.endsWith('"')) ||
			(val.startsWith("'") && val.endsWith("'"))
		) {
			val = val.slice(1, -1);
		}
		out.set(key, val);
	}
	return out;
}

function serializeEnv(values: Map<string, string>): string {
	const lines: string[] = [
		"# Generated by `bun run setup` — edit freely, re-run setup to update.",
		"",
	];
	for (const [k, v] of values) {
		// Quote if value contains spaces or special chars
		const needsQuote = /[\s#"'`$\\]/.test(v);
		lines.push(`${k}=${needsQuote ? `"${v.replaceAll('"', '\\"')}"` : v}`);
	}
	return `${lines.join("\n")}\n`;
}

function runConvex(args: string[]): {
	ok: boolean;
	stdout: string;
	stderr: string;
} {
	const res = spawnSync("bunx", ["convex", ...args], {
		cwd: ROOT,
		stdio: ["inherit", "pipe", "pipe"],
		encoding: "utf-8",
	});
	return {
		ok: res.status === 0,
		stdout: res.stdout ?? "",
		stderr: res.stderr ?? "",
	};
}

function isValidUrl(s: string): boolean {
	try {
		new URL(s);
		return true;
	} catch {
		return false;
	}
}

function deriveConvexSiteUrl(cloudUrl: string): string {
	return cloudUrl.replace(".convex.cloud", ".convex.site");
}

// Génère la paire RS256 attendue par Convex Auth (JWT_PRIVATE_KEY + JWKS).
// Reproduit node_modules/@convex-dev/auth/src/cli/generateKeys.ts.
async function generateAuthKeys(): Promise<{
	JWT_PRIVATE_KEY: string;
	JWKS: string;
}> {
	const keys = await generateKeyPair("RS256", { extractable: true });
	const privateKey = await exportPKCS8(keys.privateKey);
	const publicKey = await exportJWK(keys.publicKey);
	const jwks = JSON.stringify({ keys: [{ use: "sig", ...publicKey }] });
	return {
		JWT_PRIVATE_KEY: privateKey.trimEnd().replace(/\n/g, " "),
		JWKS: jwks,
	};
}

async function main() {
	header("iClone setup");
	info("This wizard sets up your local environment + Convex deployment.");
	info("You can re-run it anytime: bun run setup");

	// ─── 1. Bun ──────────────────────────────────────────────
	header("1/5 — Prerequisites");
	const bunVer = process.versions.bun;
	if (!bunVer) {
		fail("Bun not detected. Install: https://bun.sh");
	}
	ok(`Bun v${bunVer}`);

	// ─── 2. Convex ───────────────────────────────────────────
	header("2/5 — Convex deployment");
	const existingEnv = existsSync(ENV_PATH)
		? parseEnv(readFileSync(ENV_PATH, "utf-8"))
		: new Map<string, string>();

	const hasConvexUrl = existingEnv.has("NEXT_PUBLIC_CONVEX_URL");

	if (hasConvexUrl) {
		ok(`Convex URL already set: ${existingEnv.get("NEXT_PUBLIC_CONVEX_URL")}`);
	} else {
		info("Launching `bunx convex dev --once` — this will:");
		info("  • Open your browser to log in to Convex");
		info("  • Ask you to create or select a project");
		info("  • Write CONVEX_DEPLOYMENT + NEXT_PUBLIC_CONVEX_URL to .env.local");
		const cont = await confirm("Continue?");
		if (!cont) fail("Aborted.");

		const res = runConvex(["dev", "--once"]);
		if (!res.ok) {
			warn("convex dev exited with errors — check the output above.");
			warn("You can re-run setup once it succeeds.");
			process.exit(1);
		}
		ok("Convex initialised.");
	}

	// Reload env after convex potentially wrote to it
	const envNow = existsSync(ENV_PATH)
		? parseEnv(readFileSync(ENV_PATH, "utf-8"))
		: new Map<string, string>();

	const cloudUrl = envNow.get("NEXT_PUBLIC_CONVEX_URL");
	if (!cloudUrl || !isValidUrl(cloudUrl)) {
		fail(
			"NEXT_PUBLIC_CONVEX_URL missing or invalid — run `bunx convex dev` first.",
		);
	}

	const siteUrl = deriveConvexSiteUrl(cloudUrl);
	envNow.set("NEXT_PUBLIC_CONVEX_SITE_URL", siteUrl);
	ok(`Convex site URL: ${siteUrl}`);

	// ─── 2b. Convex Auth keys (JWT_PRIVATE_KEY + JWKS) ────────
	// Sans ces clés, le sign-in/sign-up renvoie 400 "Missing JWT_PRIVATE_KEY".
	// `bunx convex dev` ne les génère PAS — c'est au setup de le faire.
	header("Convex Auth keys");
	const existingJwt = runConvex(["env", "get", "JWT_PRIVATE_KEY"]);
	if (existingJwt.ok && existingJwt.stdout.trim()) {
		ok("Auth keys already set — skipping.");
	} else {
		info("Generating an RS256 keypair for Convex Auth…");
		const { JWT_PRIVATE_KEY, JWKS } = await generateAuthKeys();
		// "--" = fin des options : la clé PKCS8 commence par "-----BEGIN…",
		// que le parseur de la CLI Convex prendrait sinon pour un flag.
		const rk = runConvex([
			"env",
			"set",
			"JWT_PRIVATE_KEY",
			"--",
			JWT_PRIVATE_KEY,
		]);
		if (!rk.ok) warn("Could not set JWT_PRIVATE_KEY on Convex.");
		const rj = runConvex(["env", "set", "JWKS", "--", JWKS]);
		if (!rj.ok) warn("Could not set JWKS on Convex.");
		ok("Convex Auth keys generated + set.");
	}

	// ─── 3. App base URL ─────────────────────────────────────
	header("3/5 — App base URL");
	const currentBase = envNow.get("APP_BASE_URL") ?? "http://localhost:3000";
	const baseUrl = await ask(
		"Public URL of this Next.js app (dev=http://localhost:3000)",
		currentBase,
	);
	envNow.set("APP_BASE_URL", baseUrl);
	ok(`APP_BASE_URL=${baseUrl}`);

	// ─── 4. Google OAuth (optional) ──────────────────────────
	header("4/5 — Google OAuth (Calendar sync)");
	info(
		"Without Google, hosts cannot connect a calendar. You can skip and add later.",
	);
	info("Setup guide: docs/INSTALL.md §5 (Google Cloud Console)");
	const setupGoogle = await confirm("Configure Google OAuth now?", true);

	if (setupGoogle) {
		const existingId = envNow.get("GOOGLE_CLIENT_ID") ?? "";
		const clientId = await ask(
			"Google OAuth Client ID",
			existingId || undefined,
		);
		const clientSecret = await askSecret("Google OAuth Client Secret");
		envNow.set("GOOGLE_CLIENT_ID", clientId);

		info("Setting Convex-side secrets…");
		const r1 = runConvex(["env", "set", "GOOGLE_CLIENT_ID", clientId]);
		if (!r1.ok) warn("Could not set GOOGLE_CLIENT_ID on Convex.");
		const r2 = runConvex(["env", "set", "GOOGLE_CLIENT_SECRET", clientSecret]);
		if (!r2.ok) warn("Could not set GOOGLE_CLIENT_SECRET on Convex.");

		// State secret
		const stateSecret = randomBytes(32).toString("hex");
		const r3 = runConvex([
			"env",
			"set",
			"GOOGLE_OAUTH_STATE_SECRET",
			stateSecret,
		]);
		if (!r3.ok) warn("Could not set GOOGLE_OAUTH_STATE_SECRET on Convex.");
		// Même secret côté Next (.env.local) — requis par src/lib/oauth-state.ts (I3).
		envNow.set("GOOGLE_OAUTH_STATE_SECRET", stateSecret);

		ok("Google OAuth configured.");
		warn(`Add this redirect URI in Google Cloud Console:`);
		warn(`  ${siteUrl}/google/callback`);
	} else {
		info("Skipped Google OAuth.");
	}

	// ─── 5. Resend ───────────────────────────────────────────
	header("5/5 — Resend (transactional email)");
	info("Required for booking confirmations + reminders.");
	info("Get an API key: https://resend.com/api-keys");
	const setupResend = await confirm("Configure Resend now?", true);

	if (setupResend) {
		const resendKey = await askSecret("Resend API key (starts with re_)");
		const fromEmail = await ask(
			"Resend From email (e.g. noreply@your-domain.com)",
			"onboarding@resend.dev",
		);

		const r1 = runConvex(["env", "set", "RESEND_API_KEY", resendKey]);
		if (!r1.ok) warn("Could not set RESEND_API_KEY on Convex.");
		const r2 = runConvex(["env", "set", "RESEND_FROM_EMAIL", fromEmail]);
		if (!r2.ok) warn("Could not set RESEND_FROM_EMAIL on Convex.");

		ok("Resend configured.");
		if (fromEmail.includes("onboarding@resend.dev")) {
			warn("Using Resend sandbox sender — emails ONLY reach your own account.");
			warn("Verify a domain in Resend before sending to real prospects.");
		}
	} else {
		info("Skipped Resend.");
	}

	// ─── 6. Signup allowlist (admin du client) ───────────────
	header("Admin / allowlist d'inscription");
	info("Seuls les emails de l'allowlist peuvent créer un compte. Le premier à");
	info("s'inscrire devient admin (owner) de cette instance.");
	const adminEmail = await ask(
		"Email admin (owner de cette instance) — devient admin au 1er signup",
	);
	if (adminEmail) {
		const existing = runConvex(["env", "get", "SIGNUP_ALLOWED_EMAILS"]);
		const current =
			existing.ok && existing.stdout.trim() ? existing.stdout.trim() : "";
		const merged = Array.from(
			new Set(
				`${current},${adminEmail}`
					.split(",")
					.map((e) => e.trim().toLowerCase())
					.filter(Boolean),
			),
		).join(",");
		const r = runConvex(["env", "set", "SIGNUP_ALLOWED_EMAILS", merged]);
		if (!r.ok) warn("Could not set SIGNUP_ALLOWED_EMAILS on Convex.");
		else ok(`Allowlist inscription : ${merged}`);
	} else {
		warn("Aucun email admin → SIGNUP_ALLOWED_EMAILS vide = inscription FERMÉE");
		warn("(fail-closed). À définir avant de livrer l'instance.");
	}

	// ─── Write .env.local ────────────────────────────────────
	writeFileSync(ENV_PATH, serializeEnv(envNow), "utf-8");
	ok(".env.local written.");

	// ─── Final summary ───────────────────────────────────────
	header("Done!");
	log("");
	log(`${c.bold}Next steps:${c.reset}`);
	log(`  ${c.cyan}1.${c.reset} Start dev servers in two terminals:`);
	log(`     ${c.dim}# Terminal 1${c.reset}`);
	log(`     bunx convex dev`);
	log(`     ${c.dim}# Terminal 2${c.reset}`);
	log(`     bun run dev`);
	log("");
	log(
		`  ${c.cyan}2.${c.reset} Open http://localhost:3000/signup and create your first account.`,
	);
	log("");
	log(`  ${c.cyan}3.${c.reset} Promote yourself to admin:`);
	log(`     ${c.dim}# Replace with the email you signed up with${c.reset}`);
	log(
		`     bunx convex run migrations:promoteAdmin '{"email":"you@example.com"}'`,
	);
	log("");
	log(
		`  ${c.cyan}4.${c.reset} Login at http://localhost:3000/login and configure:`,
	);
	log(`     • Settings → Calendar → connect Google`);
	log(`     • Settings → Availability → set your weekly slots`);
	log(`     • Events → create your first booking page`);
	log("");
	log(`${c.dim}Full docs: docs/INSTALL.md${c.reset}`);
	log("");
	rl.close();
}

main().catch((err) => {
	console.error(`${c.red}Setup failed:${c.reset}`, err);
	rl.close();
	process.exit(1);
});
